internal var string1 = "name: ${name}"
internal var string2 = "full name: ${name} ${lastName}"
internal var string3 = "name: ${name ?: lastName}"
internal var string4 = "name: ${user?.name ?: ("-" + lastName)}"
internal var string5 = "name: ${list.map({ it.name }) ?: "empty"} \tactive: ${active}"
internal var unicode = "A special \u016C char and interpolator ${name}"
